name: coop

on:
  pull_request:
  push:
    branches:
      - 'coop-deploy'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v2.4.0

      - name: Install Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16.x'

      - name: Install npm packages
        run: |
          set -e
          npm install

      - name: Build UI
        run: |
          set -e
          npm run build:production

      - name: Run tests
        run: |
          set -e
          npm test

      - name: Run eslint
        run: |
          set -e
          npm run lint

      - name: Generate docs
        run: |
          set -e
          npm run docs

      - name: Deploy
        if: github.repository == 'jaysc/tww-rando-tracker' && github.ref == 'refs/heads/coop-deploy'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          personal_token: ${{ secrets.GH_PAGES_DEPLOY }}
          force_orphan: true
          publish_branch: gh-pages-main
          publish_dir: ./dist
